### ISSUE TITLE
feat: cache repo?

### ISSUE THREAD

**Issue by carlmontanari** [srl-labs/clabernetes#11]
basically: can we either use (perhaps via a proxy?) the host clusters container runtime for storing/pulling images or can/should we implement/add an (optional) image cache. the reason/driver for this is that we are stupidly pulling the images every time because each time we spin up a launcher container (dind container) that docker daemon is brand new and has no images and no access to host cluster!

**Comment by hellt** [comment]
this would be cool. I tapped into it for a quick sec but nothing jumped out immediately

**Comment by carlmontanari** [comment]
gunna close this and use #24 to track it as I *think* we're basically leaning toward having an optional docker push/pull (docker.io/registry:2) and clab/clabverter/some cli tool to load images to that (like kind load-docker-image or w/e that command is).

in any case, I think there is more thought in #24 and its all related since this would basically obviate the need for us to directly support private registries (and thus not have to deal w/ crews!) by just letting users use skopeo to copy images from their reg to ours or just pull/re-tag/push etc.
