### ISSUE TITLE
Add imagePullSecrets option to clabverter

### ISSUE THREAD

**Issue by SimPeccaud** [srl-labs/clabernetes#124]
I didn't find any robust way to have this set in clabverter output.

Code is ready.

**Comment by carlmontanari** [comment]
let it rip I think! though will defer to roman as he is the clabverter wrangler for sure! :D

**Comment by SimPeccaud** [comment]
It's about setting this value in Topology: `spec.imagePull.pullSecrets[0] = "regcred"` when invoking clabverter with `--imagePullSecrets="regcred"`.

`regcred` is the name of the secret created in `clabernetes` namespace of type `kubernetes.io/dockerconfigjson` that holds docker auth info to secure registry.
