### ISSUE TITLE
feat: tee clab container logs to launcher stdout

### ISSUE THREAD

**Issue by carlmontanari** [srl-labs/clabernetes#14]
basically need to tee the logs from the actual network container (i.e. srl/ceos/etc.) to either a file or maybe to stdout of the launcher pod so that kubectl logs gets that info and/or so users can k exec tail the log... tbd which is best/better?

**Comment by hellt** [comment]
this seems to be done in #30 ?

**Comment by carlmontanari** [comment]
hah I did the same yesterday -- issue title/descriptions were like 99% same/same my bad 🤡

**Comment by carlmontanari** [comment]
follow up in #57
