### ISSUE TITLE
not running behind corporate proxy  

### ISSUE THREAD

**Issue by grobile** [srl-labs/clabernetes#175]
When we try to run a clabernetes environment on a cluster behind a corporate proxy, pods are ending up in "CrashLoopBackOff"
because image pull fails 

Pod logs display "containerlab | Error: Error response from daemon: Get "https://ghcr.io/v2/": dial tcp 140.82.121.33:443: i/o timeout" for example. 
It seems that proxy setting ignored when docker images getting pulled, thats what i can observe on the Host running a tcpdump.

Running it on a machine with direct internet access we do not have issues

**Comment by hellt** [comment]
The proxy should be configured in the [daemon.json file ](https://docs.docker.com/engine/daemon/proxy/#daemon-configuration). You can mount one in your CR - https://doc.crds.dev/github.com/srl-labs/clabernetes/clabernetes.containerlab.dev/Config/v1alpha1@v0.2.3#spec-imagePull-dockerDaemonConfig

**Comment by grobile** [comment]
have tried that. created a secret with 
"kubectl create secret generic dockerconfigsecret3 \
    --from-literal=.dockerconfigjson='{"daemon.json": { "proxies": {"http-proxy": "http://10.10.10.8:3128",
	"https-proxy": "http://10.10.10.8:3128",
	"no-proxy": "*.test.example.com,.example.org,127.0.0.0/8"}}}' \
    --type=kubernetes.io/dockerconfigjson \
    --namespace c9s-vlan"

and referenced that in the yaml file 

...
---
apiVersion: clabernetes.containerlab.dev/v1alpha1
kind: Topology
metadata:
  name: vlan
  namespace: c9s-vlan
spec:
  imagePull:
    dockerDaemonConfig: dockerconfigsecret3
  deployment:
    filesFromConfigMap:
        client1:
          - filePath: configs/client.sh
            configMapName: vlan-client1-files
            configMapPath: configs-client.sh
            mode: execute
        client2:
          - filePath: configs/client.sh
            configMapName: vlan-client2-files
            configMapPath: configs-client.sh
            mode: execute
        srl1:
          - filePath: configs/srl.cfg
            configMapName: vlan-srl1-startup-config
            configMapPath: startup-config
            mode: read
...

I can see in tcpdump, still not using the proxy. :-(

What is my misstake?

**Comment by carlmontanari** [comment]
cant possibly know

you could...

- make sure the secret got mounted correctly
- verify that the config works in non-c9s setup
- try setting proxy in the user config instead of daemon config.

**Comment by grobile** [comment]
got the problem solved in my case with a configMap containing the neccesary daemon.json values and maped that to the deploymnet

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: daemon-config
  namespace: c9s-vlan
data:
  daemon.json: |-
    {
      "proxies": {
            "http-proxy": "http://10.10.10.3:3128",
            "https-proxy": "http://10.10.10.3:3128",
            "no-proxy": "*.test.example.com,.example.org,127.0.0.0/8"
      }
    }
---
apiVersion: clabernetes.containerlab.dev/v1alpha1
kind: Topology
metadata:
  name: vlan
  namespace: c9s-vlan
spec:
  deployment:
    filesFromConfigMap:
        client1:
          - filePath: configs/client.sh
            configMapName: vlan-client1-files
            configMapPath: configs-client.sh
            mode: execute
          - filePath: /etc/docker/daemon.json
            configMapName: daemon-config
            configMapPath: daemon.json
```

Currently i don't need authentication for the Proxy.
