### ISSUE TITLE
Cisco-iol is not supported in clabernetes (containerlab - v0.57.5)

### ISSUE THREAD

**Issue by BillyFlex** [srl-labs/clabernetes#182]
Hi, 
An upgrade of clabernetes version are schedule ? 
Thanks you

**Comment by hellt** [comment]
Hi
you can manually set containerlab version to a desired one using this https://doc.crds.dev/github.com/srl-labs/clabernetes/clabernetes.containerlab.dev/Topology/v1alpha1@v0.2.4#spec-deployment-containerlabVersion

**Comment by BillyFlex** [comment]
Thank you for your help.
It is working with this command : 
"clabverter --containerlabVersion X.XX.X"

**Comment by hellt** [comment]
yes, we exposed this flag in the clabverter as well.

So I suppose you verified that IOL is working in c9s?
