### ISSUE TITLE
feat: handle clab topo "kinds"

### ISSUE THREAD

**Issue by carlmontanari** [srl-labs/clabernetes#48]
we dont, and we need to. so... title?

**Comment by hellt** [comment]
This would also mean supporting `defaults` for a full resolution tree
`defaults -> kinds -> node`

In the long run this is definitely should be leveraging clab functions to not duplicate a considerable amount of code.

**Comment by carlmontanari** [comment]
copy

yep, I think from c9s perspective its just literally copying the stuff into the sub topology, so not really anything for c9s to do. I guess at the most complicated end we could parse the kinds and only put the relevant kind in the sub topo but for pass 1 I dont think thats even needed.

**Comment by carlmontanari** [comment]
I believe this is sorted now as we include kinds/defaults from parent topo into sub topos, so ima close for now!
